language: php
php:
  - 5.3
  - 5.4
before_script:
  - wget http://getcomposer.org/composer.phar
  - wget wget http://pear.phpunit.de/get/phpunit.phar && chmod +x phpunit.phar
  - php composer.phar install 
script: phpunit.phar
